/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenaiProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "exam-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "exam-configure-problems": {
      "name": string
      "type": "sst.aws.Function"
    }
    "exam-file-problem-uploaded": {
      "name": string
      "type": "sst.aws.Function"
    }
    "exam-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "generate-pdf": {
      "name": string
      "type": "sst.aws.Function"
    }
    "main": {
      "name": string
      "type": "sst.aws.Function"
    }
    "organization-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "pdf-split-to-images": {
      "name": string
      "type": "sst.aws.Function"
    }
    "pre-token-generation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "users": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "users-client": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}